### ISSUE TITLE
Bucketeer (and other) credentials exposed

### ISSUE THREAD

**Issue by csquared** [cornell-dti/events-backend#31]
https://github.com/cornell-dti/events-backend/blob/f6bb5f79ef82bbe4504dd92914278f71d07ab624/events_backend/settings_secrets.py#L3-L4

Hey Guys!
Chris from Bucketeer here. These credentials are public and anyone can use them to administer your bucket. I've taken care of rolling them in your Heroku app.
Please look into how to store credentials without checking them into git in plaintext.
Cheers,
Chris

**Comment by rockon999** [comment]
@csquared Hi Chris thanks for the alert! It looks like a developer made a rather large mistake here. I've cleaned up the writable refs and will be reaching out to GitHub to cleanup the read-only.

In the future feel free to reach out to us directly at hello@cornelldti.org

Thanks again,
Evan

**Comment by rockon999** [comment]
Repo cleaned.
