### ISSUE TITLE
Don't pull images from external, non-stable links.

### ISSUE THREAD

**Issue by rockon999** [cornell-dti/events-backend#62]
You're loading the App Store and Play Store from Wikipedia links, which are not stable and not intended to be loaded in this way. You should add these assets to your site. Currently, the Play Store logo is broken as a result 

Example of external load: https://github.com/cornell-dti/events-backend/blob/master/events_frontend/src/Landing.js#L22

The Play Store assets can be found here: https://play.google.com/intl/en_us/badges/

**Comment by SamChou19815** [comment]
The problem is already fixed.
