### ISSUE TITLE
Remove Commented Backend Code

### ISSUE THREAD

**Issue by SamChou19815** [cornell-dti/events-backend#78]
These code should either be revitalized or killed to avoid future confusion.

TODO List:

- [ ] Example 1
https://github.com/cornell-dti/events-backend/blob/71b5608e8f06a4b22cce3fa5d129a543f74bafe2/events_backend/app/forms.py#L66-L79
- [ ] Example 2
https://github.com/cornell-dti/events-backend/blob/71b5608e8f06a4b22cce3fa5d129a543f74bafe2/events_backend/app/models.py#L122-L136
https://github.com/cornell-dti/events-backend/blob/71b5608e8f06a4b22cce3fa5d129a543f74bafe2/events_backend/app/models.py#L245-L260
- [ ] Example 3
https://github.com/cornell-dti/events-backend/blob/71b5608e8f06a4b22cce3fa5d129a543f74bafe2/events_backend/app/serializers.py#L12
- [ ] Example 4
https://github.com/cornell-dti/events-backend/blob/71b5608e8f06a4b22cce3fa5d129a543f74bafe2/events_backend/app/urls.py#L30-L43
- [ ] Example 5
https://github.com/cornell-dti/events-backend/blob/71b5608e8f06a4b22cce3fa5d129a543f74bafe2/events_backend/app/views.py#L424-L438

**Comment by EmadBinAbid** [comment]
I am working on this issue!

**Comment by SamChou19815** [comment]
closing since no one is maintaining the backend any more :(
